### ISSUE TITLE
Make pause/play button actually pause the song

### ISSUE THREAD

**Issue by amirsahabi** [amirsahabi/djesaac#11]
Current functionality of the pause button is to actually stop and restart the song, would make more intuitive sense to just pause the song.

**Comment by amirsahabi** [comment]
@cobrobrown @jessicakwong pygame only supports setting offset positions when playing a song for mp3 and ogg format songs. Is it possible to do analysis and playback on mp3 files instead of wavs? Otherwise, pausing isn't really possible.

**Comment by cobrobrown** [comment]
Yes. Can youtube_dl download as an mp3? We can convert to wav in preprocessing for preprocessing only, then send the led value arrays to dbmonitor just like we are now.

**Comment by amirsahabi** [comment]
@cobrobrown youtube-dl currently downloads songs as mp3s, and then we convert them to wav files. It feels like keeping both a copy of the wav and the mp3 file would be a waste of space.

**Comment by amirsahabi** [comment]
@cobrobrown Can you verify the latest changes (6c2c5c3) didn't affect the lightshow preprocessing?
