### ISSUE TITLE
New songs added to the queue don't load correctly in real time

### ISSUE THREAD

**Issue by amirsahabi** [amirsahabi/djesaac#13]
Looks like the latest commit b274e6b9ad0e7ea95f82b171777f1b5efb5f78bf didn't handle new events being handled (add a song to the queue and it loads in the old table format, not the new one). @jessicakwong do you want me to fix this or can you take care of it.

**Comment by jessicakwong** [comment]
Oh I got this. Thanks for the catch.

**Comment by jessicakwong** [comment]
I'm gonna keep testing this. I feel like its not updating like before.

**Comment by amirsahabi** [comment]
@jessicakwong Has this been fixed?

**Comment by jessicakwong** [comment]
Still making sure all the kinks are fixed. 

Jessica
