### ISSUE TITLE
Weird display when adding a song 

### ISSUE THREAD

**Issue by amirsahabi** [amirsahabi/djesaac#16]
See attachment for display. Added this song to be played. https://www.youtube.com/watch?v=U7soh5-EjGY

@jessicakwong Is this at all related to the changing of the icons when you resize the page stuff?

![weird](https://cloud.githubusercontent.com/assets/18159135/26234212/d1c8056a-3c17-11e7-8485-3800a4ae5881.png)

**Comment by jessicakwong** [comment]
I'll get on it tomorrow. It has something to do with auto sizing the columns.

Jessica

**Comment by jessicakwong** [comment]
I defined the width of the 1st column. Let me know if you're still having this problem. 

![screen shot 2017-05-23 at 9 59 35 am](https://cloud.githubusercontent.com/assets/12984214/26366113/b412b274-3f9e-11e7-843c-86eb1fdd97b4.png)
![screen shot 2017-05-23 at 10 00 02 am](https://cloud.githubusercontent.com/assets/12984214/26366114/b41d8bc2-3f9e-11e7-9bc4-02b714c425be.png)
