### ISSUE TITLE
Page updating issues

### ISSUE THREAD

**Issue by amirsahabi** [amirsahabi/djesaac#18]
Clicking remove removes the song from the database but doesn't remove from the list on the webpage.

Also songs are being added into the queue with different styling? Any idea why this might be happening @jessicakwong

**Comment by jessicakwong** [comment]
I'll try to recreate the issue 

Jessica

**Comment by amirsahabi** [comment]
Must've been some caching issue on my end, looks like this is working now.

**Comment by amirsahabi** [comment]
Actually just kidding, when you add a song with a song already playing (i.e. it goes into the playlist), the title is being loaded as text, not as a link @jessicakwong

**Comment by jessicakwong** [comment]
Ok thanks for pointing that out. 

Jessica
