### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by amirsahabi** [amirsahabi/djesaac#4]
Sometimes the arduino doesn't log to the default port, would be nice to change the port and pin locations through the UI.

**Comment by cobrobrown** [comment]
Also, a fine tuning option so the host can lock the lights into the beat of the song.

**Comment by amirsahabi** [comment]
@jessicakwong Is it possible to give any sort of visual confirmation when the settings save goes through? Like maybe turn the save text green or something? Red if the settings was unsuccessful?

**Comment by jessicakwong** [comment]
@amirsahabi Good idea! Will look into it.
